import informationStore from "@/stores/informationStore";
import { observer } from "mobx-react-lite";
import Head from "next/head";

const Home = observer(() => {
  function hsndleSubmit(event: React.FormEvent) {
    event.preventDefault();
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          width: "100%",
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          gap: "1rem",
        }}
      >
        <form
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "0.5rem",
          }}
          onSubmit={hsndleSubmit}
        >
          <input
            type="text"
            placeholder="nome"
            value={informationStore.data.nome}
            onChange={(event) => {
              informationStore.setNome(event.target.value);
            }}
          />

          <input type="text" placeholder="email" />
          <input type="text" placeholder="telefone" />

          <input type="text" placeholder="dependent 01" />
          <input type="text" placeholder="dependent 02" />
          <input type="text" placeholder="dependent 03" />

          <button type="submit">enviar</button>
        </form>

        <div>
          <ul>
            <li>nome: {informationStore.data.nome}</li>
            <li>telefone: {informationStore.data.telefone}</li>
            <li>email: {informationStore.data.email}</li>
          </ul>
          <ul>
            {informationStore.data.dependentes.map((dependente, index) => (
              <li key={index}>
                dependente0{index + 1}: {dependente.nome} |{" "}
                {dependente.telefone}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
});

export default Home;
